version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./gateway-service/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - member-service
      - trip-service
      - exchange-service
      - alarm-service

  member-service:
    build:
      context: .
      dockerfile: ./module-member/Dockerfile
    container_name: member-service
    ports:
      - "8081:8081"
    networks:
      - my-network

  trip-service:
    build:
      context: .
      dockerfile: ./module-trip/Dockerfile
    container_name: trip-service
    ports:
      - "8082:8082"
    networks:
      - my-network

  exchange-service:
    build:
      context: .
      dockerfile: ./module-exchange/Dockerfile
    container_name: exchange-service
    ports:
      - "8083:8083"
    networks:
      - my-network

  alarm-service:
    build:
      context: .
      dockerfile: ./module-alarm/Dockerfile
    container_name: alarm-service
    ports:
      - "8084:8084"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
