spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:mysql://localhost:3306/trip_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082