spring:
  application:
    name: module-alarm

  datasource:
    url: jdbc:mysql://localhost:3306/ttt
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8084