spring:
  application:
    name: module-alarm

  datasource:
    url: jdbc:mysql://localhost:3306/trip_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost  # 환경변수에서 가져오기
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/