server:
  port: 8084

spring:
  application:
    name: alarm-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${ALARM_INSTANCE_IP_ADDRESS:localhost}

FIREBASE_KEY: "/app/serviceAccountKey.json"