server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  datasource:
    url: none
    driver-class-name: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka를 통해 서비스 검색 활성화
          lower-case-service-id: true  # 서비스 ID를 소문자로 변환하여 Eureka와 일치시킴
      routes:
        - id: module-member
          uri: lb://module-member  # Eureka에서 검색
          predicates:
            - Path=/api/members/**
        - id: module-trip
          uri: lb://module-trip
          predicates:
            - Path=/api/trips/**
        - id: module-trip-accounts
          uri: lb://module-trip
          predicates:
            - Path=/api/accounts/**
        - id: module-exchange
          uri: lb://module-exchange
          predicates:
            - Path=/api/exchanges/**
        - id: module-alarm
          uri: lb://module-alarm
          predicates:
            - Path=/api/alarms/**
jwtKey:
  jwt: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost  # 환경변수에서 가져오기
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

