server:
  port: 9093

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  datasource:
    url: none
    driver-class-name: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: "http://localhost:9094"
          predicates:
            - Path=/auth/**
        - id: trip-service
          uri: "http://localhost:8083"
          predicates:
            - Path=/trips/**
