server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  datasource:
    url: none
    driver-class-name: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: "http://member-service:8081"
          predicates:
            - Path=/members/**
        - id: trip-service
          uri: "http://trip-service:8082"
          predicates:
            - Path=/trips/**
        - id: exchange-service
          uri: "http://exchange-service:8083"
          predicates:
            - Path=/exchanges/**
        - id: alarm-service
          uri: "http://alarm-service:8084"
          predicates:
            - Path=/alarms/**