server:
  port: 8085

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  datasource:
    url: none
    driver-class-name: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: "http://localhost:8081"
          predicates:
            - Path=/api/members/**
        - id: trip-service
          uri: "http://localhost:8082"
          predicates:
            - Path=/api/trips/**
        - id: exchange-service
          uri: "http://localhost:8083"
          predicates:
            - Path=/api/exchanges/**
        - id: alarm-service
          uri: "http://localhost:8084"
          predicates:
            - Path=/api/alarms/**