server:
  port: 8085

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  application:
    name: gateway-service

  datasource:
    url: none
    driver-class-name: none

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/**
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/trips/**
        - id: exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=/exchanges/**
        - id: alarm-service
          uri: lb://alarm-service
          predicates:
            - Path=/alarms/**

eureka:
  client:
    service-url:
      defaultZone: http://54.180.235.123:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
