server:
  port: 8085

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  application:
    name: gateway-service

  datasource:
    url: none
    driver-class-name: none

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka를 통해 서비스 검색 활성화
          lower-case-service-id: true  # 서비스 ID를 소문자로 변환하여 Eureka와 일치시킴
      routes:
        - id: member-service
          uri: http://triptransfertrade.shop/api/members  # ALB 사용
          predicates:
            - Path=/api/members/**
        - id: trip-service
          uri: http://triptransfertrade.shop/api/trips  # ALB 사용
          predicates:
            - Path=/api/trips/**
        - id: exchange-service
          uri: http://triptransfertrade.shop/api/exchanges  # ALB 사용
          predicates:
            - Path=/api/exchanges/**
        - id: alarm-service
          uri: http://triptransfertrade.shop/api/alarms  # ALB 사용
          predicates:
            - Path=/api/alarms/**

eureka:
  client:
    service-url:
      defaultZone: http://54.180.235.123:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false  # IP가 아닌 도메인 기반으로 Eureka 등록
    hostname: triptransfertrade.shop  # ALB 도메인 사용
