server:
  port: 8761  # Eureka 기본 포트
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: your-password
    key-store-type: PKCS12
spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS:localhost}  # 환경변수에서 가져오기
  client:
    register-with-eureka: false  # Eureka 서버 자체는 자신을 등록할 필요 없음
    fetch-registry: false  # 다른 Eureka 서버의 정보를 가져올 필요 없음
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  server:
    enable-self-preservation: false  # 네트워크 장애 시 기존 정보 유지
    eviction-interval-timer-in-ms: 5000